services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hospital_db
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-u","root","-ppassword"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  flask-app-1:
    build: ./app
    ports:
      - "6000:6000"
    volumes:
      - ./app:/app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=hospital_db
      - HOSPITAL_NAME=Vasant Kunj Hospital
      - PORT=6000
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: requirements.txt


volumes:
  mysql_data:
    driver: local